name: Python CI

on:
  push:
    branches:
      - main
      - "feat/**"
      - "fix/**"

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          version: latest

      - name: Setup Python
        run: uv python install ${{ matrix.python-version }}

      - name: Install Dependencies
        run: uv sync --dev --python ${{ matrix.python-version }}

      - name: Run Tests
        run: uv run pytest